### ISSUE TITLE
Question: How to create multiple instances of a component?

### ISSUE THREAD

**Issue by amithegde** [mrpmorris/blazor-fluxor#69]
May be something I missed. I included `<Counter></Counter>` on `index.razpr` and now both the instances of counter subscribe to same state. Depending on use case, this will be useful. In some cases we would want the ability to create multiple instances of a component and have their own individual state. How to do it?

**Comment by mrpmorris** [comment]
I'd do this

1. Rename CounterFeature to CountersFeature (plural) - same for CounterState, and the Store.Counter namespace.
2. Instead of an int, make the property in CountersState a `Dictionary<string, int>`
3: Add a method to CountersState that does a `TryGetValue` on the dictionary. So something like `GetValueOrDefault(string counterId)`
4: Make sure your IncrementCounterAction has a new `CounterId` property in it
5. Make sure your IncrementCounterReducer increments the correct value in the `Dictionary<string, int>` based on that `CounterId` - make sure you add the value 1 to the dictionary if it didn't already exist.
6. Add a `[Parameter] public string CounterId { get; set; }` to your component, which you'll use in your view (`State.Value.GetValueOrDefault(CounterId)`) and also when creating your `IncrementCounterAction` to dispatch.

**Comment by xperiandri** [comment]
What about performance?
If I have 30 instances of component each of them will be notified on change of state of any other instance.
Won't they be overusing resources?

**Comment by mrpmorris** [comment]
If you are ever worried about a Blazor component re-rendering too often you can store the previous counter value in the component, and then override `ShouldRender()` which only returns true if the new value is different to the last value.
